#include "matrix_pattern.h"

static const char *const SAFETY_CAR_MATRIX[MATRIX_PATTERN_SIZE] = {
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXWWWWWWXXXXXXWWWWWWXXXXXYY",
    "YYXXXXXWWWWWWXXXXXXWWWWWWXXXXXYY",
    "YYXXXWWXXXXXXWWXXWWXXXXXXWWXXXYY",
    "YYXXXWWXXXXXXWWXXWWXXXXXXWWXXXYY",
    "YYXXXWWXXXXXXXXXXWWXXXXXXXXXXXYY",
    "YYXXXWWXXXXXXXXXXWWXXXXXXXXXXXYY",
    "YYXXXWWXXXXXXXXXXWWXXXXXXXXXXXYY",
    "YYXXXWWXXXXXXXXXXWWXXXXXXXXXXXYY",
    "YYXXXXXWWWWWWXXXXWWXXXXXXXXXXXYY",
    "YYXXXXXWWWWWWXXXXWWXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXWWXXWWXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXWWXXWWXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXWWXXWWXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXWWXXWWXXXXXXXXXXXYY",
    "YYXXXWWXXXXXXWWXXWWXXXXXXWWXXXYY",
    "YYXXXWWXXXXXXWWXXWWXXXXXXWWXXXYY",
    "YYXXXXXWWWWWWXXXXXXWWWWWWXXXXXYY",
    "YYXXXXXWWWWWWXXXXXXWWWWWWXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
};

static const char *const VSC_MATRIX[MATRIX_PATTERN_SIZE] = {
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXWWXXXXWWXXXWWWWWWXXXWWWWWWXYY",
    "YYXWWXXXXWWXXXWWWWWWXXXWWWWWWXYY",
    "YYXWWXXXXWWXWWXXXXXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXWWXXXXXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXWWXXXXXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXWWXXXXXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXXXWWWWXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXXXWWWWXXXWWXXXXXXXYY",
    "YYXWWXXXXWWXXXXXXXWWXWWXXXXXXXYY",
    "YYXWWXXXXWWXXXXXXXWWXWWXXXXXXXYY",
    "YYXXXWWWWXXXXXXXXXWWXWWXXXXXXXYY",
    "YYXXXWWWWXXXXXXXXXWWXWWXXXXXXXYY",
    "YYXXXWWWWXXXWWWWWWXXXXXWWWWWWXYY",
    "YYXXXWWWWXXXWWWWWWXXXXXWWWWWWXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYXXXXXXXXXXXXXXXXXXXXXXXXXXXXYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
};

char matrix_pattern_get_pixel(size_t row, size_t column, void *user_data) {
    const matrix_pattern_t *pattern = static_cast<const matrix_pattern_t *>(user_data);
    if (pattern == nullptr || row >= MATRIX_PATTERN_SIZE || column >= MATRIX_PATTERN_SIZE) {
        return '.';
    }

    switch (pattern->type) {
        case MATRIX_PATTERN_SOLID:
            return pattern->visible ? pattern->pixel : '.';
        case MATRIX_PATTERN_DOUBLE_YELLOW:
            return pattern->triangle_state ? (column >= row ? pattern->pixel : '.')
                                           : (row >= column ? pattern->pixel : '.');
        case MATRIX_PATTERN_SAFETY_CAR:
            return SAFETY_CAR_MATRIX[row][column];
        case MATRIX_PATTERN_VSC:
            return VSC_MATRIX[row][column];
    }
    return '.';
}